# Global allowlist
[allowlist]
  description = "Testdata sample cert files"
  paths = [
      "^sampleCerts/(.*?)$",
      "^testdata/examples/(.*?)$",
      "^scripts/federation/(.*?)$",
      ".gitleaks.toml",
  ]
